b

AfterBuild/Select:01j6

DUMMY_NAME_NOT_USED:0
AfterBuild/Select_1:0r˜
ñ
#
!Prepare/words/words_start_index:0
Prepare/words/words_max_end:0$
"Prepare/words/words_sequence_end:0")
'Prepare/words/words_total_batch_count:0*,
*Prepare/words/words_unpadded_start_index:02*
(Prepare/words/words_unpadded_end_index:0¡
+
)Prepare/syllables/syllables_start_index:0'
%Prepare/syllables/syllables_max_end:0,
*Prepare/syllables/syllables_sequence_end:0"1
/Prepare/syllables/syllables_total_batch_count:0*4
2Prepare/syllables/syllables_unpadded_start_index:022
0Prepare/syllables/syllables_unpadded_end_index:0ý
%
#Prepare/phones/phones_start_index:0!
Prepare/phones/phones_max_end:0&
$Prepare/phones/phones_sequence_end:0"+
)Prepare/phones/phones_total_batch_count:0*.
,Prepare/phones/phones_unpadded_start_index:02,
*Prepare/phones/phones_unpadded_end_index:0šÁ0
)Prepare/sentence_linguistics_input_data:0“+
%Prepare/word_linguistics_input_data:0i"/
)Prepare/syllable_linguistics_input_data:0D*/
(Prepare/phoneme_linguistics_input_data:0ßª4
2
-Prepare/sentence_embedding_placeholder_data:0€²Z
+
%Prepare/phoneme_duration_input_data:0+
%Prepare/phoneme_duration_scale_data:0º5

merged_activations:0g
root/Op_46/concat:0g